//
// Created by molin on 10/12/2019.
//

#ifndef FOREST_TREE_EVALUATOR_LINEARIZEDRAPIDSCORER_H
#define FOREST_TREE_EVALUATOR_LINEARIZEDRAPIDSCORER_H

#endif //FOREST_TREE_EVALUATOR_LINEARIZEDRAPIDSCORER_H
